### ISSUE TITLE
Pin script failing

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-maintenance#3]
This problem has been fixed in a number of the conda-forge.github.io repo's scripts, but not this one. Time to factor out some of that code.

```
Checking slicerator-feedstock
Traceback (most recent call last):
  File "conda-forge.github.io/scripts/pin_the_slow_way.py", line 302, in <module>
    parsable_content = env.from_string(content).render(os=os)
  File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.conda/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 34, in top-level template code
  File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "conda-forge.github.io/scripts/pin_the_slow_way.py", line 257, in __getattr__
    return unicode('{}.{}'.format(self, name))
NameError: name 'unicode' is not defined
```

**Comment by pelson** [comment]
I factored out much of the code into conda-smithy in https://github.com/conda-forge/conda-smithy/pull/269. This one should be fixed.
