### ISSUE TITLE
Pin script failing

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-maintenance#5]
Uncertain on which feedstock, but the following ensued:

```
Traceback (most recent call last):
  File "/app/conda-forge.github.io/scripts/pin_the_slow_way.py", line 232, in <module>
    for feedstock, git_ref, meta_content, recipe in feedstock_gen:
  File "/app/.conda/tmp_envs/e51aaf2a2e07c87d7cc9/lib/python3.5/site-packages/conda_smithy/feedstocks.py", line 230, in feedstocks_yaml
    for repo, feedstock in feedstocks_repos(organization, feedstocks_directory, **feedstocks_repo_kwargs):
  File "/app/.conda/tmp_envs/e51aaf2a2e07c87d7cc9/lib/python3.5/site-packages/conda_smithy/feedstocks.py", line 173, in feedstocks_repos
    upstream = repo.remotes.upstream
  File "/app/.conda/tmp_envs/e51aaf2a2e07c87d7cc9/lib/python3.5/site-packages/git/util.py", line 697, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'upstream'
```

**Comment by jakirkham** [comment]
We migrated from the pinning script to [conda-forge-pinning]( https://github.com/conda-forge/conda-forge-pinning-feedstock ) as part of migrating to conda-build 3. Also we including pinnings as part of re-rendering. So this shouldn't be relevant any more.
